
import React, { useState, useEffect, useMemo } from 'react';
import { Search, X, Loader2, Layout, ArrowLeft } from 'lucide-react';
import { format } from 'date-fns';
import { useStore } from '../store/useStore';

interface BlogListProps {
  onViewChange: (view: string, id?: string) => void;
}

const BlogList: React.FC<BlogListProps> = ({ onViewChange }) => {
  const { posts, fetchPosts, isLoadingPosts } = useStore();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedTag, setSelectedTag] = useState<string | null>(null);
  const [publishedPosts, setPublishedPosts] = useState(posts);

  useEffect(() => {
    fetchPosts();
  }, [fetchPosts]);

  useEffect(() => {
    setPublishedPosts(posts.filter(p => p.status === 'PUBLISHED'));
  }, [posts]);

  const allTags = useMemo(() => {
    const tags = new Set<string>();
    publishedPosts.forEach(post => post.tags.forEach(tag => tags.add(tag)));
    return Array.from(tags).sort();
  }, [publishedPosts]);

  const filteredPosts = useMemo(() => {
    return publishedPosts.filter(post => {
      const matchesSearch = 
        post.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
        post.summary.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesTag = selectedTag ? post.tags.includes(selectedTag) : true;
      return matchesSearch && matchesTag;
    });
  }, [publishedPosts, searchQuery, selectedTag]);

  return (
    <div className="min-h-screen bg-neutral-50 dark:bg-[#050505] text-neutral-900 dark:text-white">
      {/* Header Section */}
      <div className="relative pt-24 pb-12 border-b border-neutral-200 dark:border-white/5 bg-white dark:bg-[#0a0a0a]">
        <div className="max-w-7xl mx-auto px-4">
            <h1 className="text-4xl md:text-5xl font-bold mb-4 tracking-tight">Intelligence Feed</h1>
            <p className="text-neutral-500 dark:text-neutral-400 max-w-2xl text-lg">
                Curated insights generated by the Nexis Engine. Explore the latest trends in AI and defense.
            </p>

            {/* Search and Filter Bar */}
            <div className="mt-8 flex flex-col md:flex-row gap-4 items-center">
                <div className="relative flex-1 w-full group">
                    <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-neutral-400 group-focus-within:text-orange-500 transition-colors" size={20} />
                    <input 
                        type="text" 
                        placeholder="Search intelligence database..." 
                        className="w-full bg-neutral-100 dark:bg-black border border-neutral-200 dark:border-white/10 rounded-lg py-3 pl-12 pr-4 text-neutral-900 dark:text-white focus:outline-none focus:border-orange-500 transition-all placeholder:text-neutral-500 dark:placeholder:text-neutral-600"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                    />
                    {searchQuery && (
                        <button onClick={() => setSearchQuery('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-neutral-400 hover:text-black dark:hover:text-white">
                            <X size={16} />
                        </button>
                    )}
                </div>
                
                {/* Tags */}
                <div className="flex gap-2 overflow-x-auto w-full md:w-auto pb-2 md:pb-0 scrollbar-hide">
                    <button 
                         onClick={() => setSelectedTag(null)}
                         className={`px-4 py-3 rounded-lg text-sm font-medium whitespace-nowrap transition-all border ${selectedTag === null ? 'bg-orange-500 border-orange-500 text-white dark:text-black' : 'bg-neutral-100 dark:bg-black border-neutral-200 dark:border-white/10 text-neutral-500 dark:text-neutral-400 hover:border-neutral-300 dark:hover:border-white/30'}`}
                    >
                        All Sectors
                    </button>
                    {allTags.map(tag => (
                        <button 
                            key={tag}
                            onClick={() => setSelectedTag(tag === selectedTag ? null : tag)}
                            className={`px-4 py-3 rounded-lg text-sm font-medium whitespace-nowrap transition-all border ${selectedTag === tag ? 'bg-orange-500 border-orange-500 text-white dark:text-black' : 'bg-neutral-100 dark:bg-black border-neutral-200 dark:border-white/10 text-neutral-500 dark:text-neutral-400 hover:border-neutral-300 dark:hover:border-white/30'}`}
                        >
                            {tag}
                        </button>
                    ))}
                </div>
            </div>
        </div>
      </div>

      {/* Grid */}
      <div className="max-w-7xl mx-auto px-4 py-16">
        <div className="flex items-center justify-between mb-8">
            <h2 className="text-sm font-bold text-neutral-500 uppercase tracking-widest flex items-center gap-2">
                <span className="w-2 h-2 bg-orange-500 rounded-full"></span>
                System Output ({filteredPosts.length})
            </h2>
        </div>

        {isLoadingPosts ? (
          <div className="flex justify-center py-24"><Loader2 className="animate-spin text-orange-500" size={40} /></div>
        ) : filteredPosts.length === 0 ? (
          <div className="text-center py-24 border border-dashed border-neutral-200 dark:border-white/10 rounded-xl bg-neutral-100 dark:bg-white/5">
            <div className="bg-white dark:bg-white/10 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 border border-neutral-200 dark:border-transparent">
              <Search className="h-8 w-8 text-neutral-400 dark:text-neutral-500" />
            </div>
            <h3 className="text-xl font-bold text-neutral-900 dark:text-white mb-2">No data found</h3>
            <p className="text-neutral-500">Adjust your parameters to locate intelligence.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {filteredPosts.map((post) => (
              <div 
                key={post.id} 
                onClick={() => onViewChange('post', post.id)}
                className="group cursor-pointer flex flex-col h-full bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-white/5 hover:border-orange-500/50 dark:hover:border-orange-500/50 shadow-sm hover:shadow-lg transition-all duration-300 rounded-xl overflow-hidden"
              >
                {/* Card Image - Removed opacity to fix spacing illusion */}
                <div className="h-56 relative overflow-hidden bg-neutral-100 dark:bg-neutral-800">
                  {post.coverImage ? (
                    <img src={post.coverImage} alt={post.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 block" />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center text-neutral-400 dark:text-neutral-600">
                      <Layout size={48} />
                    </div>
                  )}
                  <div className="absolute top-4 left-4 flex gap-2">
                     {post.tags.slice(0, 2).map(tag => (
                       <span key={tag} className="bg-white/90 dark:bg-black/80 backdrop-blur border border-neutral-200 dark:border-white/10 px-2 py-1 rounded text-[10px] font-bold text-orange-600 dark:text-orange-500 uppercase tracking-wider">
                         {tag}
                       </span>
                     ))}
                  </div>
                </div>

                {/* Card Content */}
                <div className="flex-1 flex flex-col p-6">
                  <div className="flex items-center text-xs text-neutral-500 mb-3 font-mono">
                    <span className="text-orange-600 dark:text-orange-500">{format(new Date(post.createdAt), 'yyyy.MM.dd')}</span>
                    <span className="mx-2 text-neutral-300 dark:text-neutral-700">|</span>
                    <span>LOG_ID_{post.id}</span>
                  </div>
                  <h3 className="text-xl font-bold text-neutral-900 dark:text-white mb-3 group-hover:text-orange-600 dark:group-hover:text-orange-500 transition-colors leading-tight">
                    {post.title}
                  </h3>
                  <p className="text-neutral-600 dark:text-neutral-400 text-sm line-clamp-3 mb-6 flex-1 leading-relaxed">
                    {post.summary}
                  </p>
                  
                  {/* Author & Footer */}
                  <div className="flex items-center justify-between pt-4 border-t border-neutral-100 dark:border-white/5 mt-auto">
                    <div className="flex items-center space-x-3">
                       <div className="h-8 w-8 rounded bg-neutral-100 dark:bg-neutral-800 flex items-center justify-center text-[10px] font-bold text-neutral-700 dark:text-white overflow-hidden border border-neutral-200 dark:border-white/10">
                         {post.authorName[0]}
                       </div>
                       <span className="text-xs font-bold text-neutral-700 dark:text-neutral-300 uppercase">{post.authorName}</span>
                    </div>
                    <div className="text-orange-600 dark:text-orange-500 text-xs font-bold flex items-center opacity-0 group-hover:opacity-100 transition-all duration-300 transform translate-x-2 group-hover:translate-x-0">
                      ACCESS_FILE <ArrowLeft className="rotate-180 ml-2 h-3 w-3" />
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default BlogList;
